title:             Occasional Investor
email:             your-email@example.com
description:       All about investing & coffee
author:            Occasional Investor
baseurl:           "/"
url:               "occasionalinvestor.github.io"

# Social Profiles
twitter_username:  occ_investor

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
